name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        with:
          heroku_api_key: "2e8947d0-cda7-4b71-a809-a1f7a0653815"
          heroku_app_name: "gay-eye" #Must be unique in Heroku
          heroku_email: "gayeye3184@hrandod.com"